{
 "title": "Flat Price FastAPI App Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Prediction Request Duration Quantiles (Total)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.05, http_request_duration_seconds_bucket{is_valid=\"true\"})",
     "legendFormat": "0.05 (valid)"
    },
    {
     "expr": "histogram_quantile(0.5, http_request_duration_seconds_bucket{is_valid=\"true\"})",
     "legendFormat": "0.5 (valid)"
    },
    {
     "expr": "histogram_quantile(0.95, http_request_duration_seconds_bucket{is_valid=\"true\"})",
     "legendFormat": "0.95 (valid)"
    },
    {
     "expr": "histogram_quantile(0.05, http_request_duration_seconds_bucket{is_valid=\"false\"})",
     "legendFormat": "0.05 (invalid)"
    },
    {
     "expr": "histogram_quantile(0.5, http_request_duration_seconds_bucket{is_valid=\"false\"})",
     "legendFormat": "0.5 (invalid)"
    },
    {
     "expr": "histogram_quantile(0.95, http_request_duration_seconds_bucket{is_valid=\"false\"})",
     "legendFormat": "0.95 (invalid)"
    }
   ]
  },
  {
   "title": "Price Prediction Quantiles (total)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.05, prediction_price_histogram_bucket)",
     "legendFormat": "0.05"
    },
    {
     "expr": "histogram_quantile(0.5, prediction_price_histogram_bucket)",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, prediction_price_histogram_bucket)",
     "legendFormat": "0.95"
    }
   ]
  },
  {
   "title": "Error Increase",
   "type": "timeseries",
   "description": "Counts the number of errors occurred over the last minute before a timestamp for each error type",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "increase(invalid_request_count_total[$__rate_interval])",
     "legendFormat": "Invalid Requests"
    },
    {
     "expr": "increase(failed_predictions_count_total[$__rate_interval])",
     "legendFormat": "Failed Predictions"
    },
    {
     "expr": "increase(too_many_requests_count_total[$__rate_interval])",
     "legendFormat": "Too Many Requests Errors"
    },
    {
     "expr": "increase(unexpected_error_count_total[$__rate_interval])",
     "legendFormat": "Unexpected Errors"
    }
   ]
  },
  {
   "title": "Prediction Request Duration Quantiles (over time window)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.05, sum(rate(http_request_duration_seconds_bucket{is_valid=\"true\"}[$__rate_interval])) by (le))",
     "legendFormat": "0.05 (valid)"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{is_valid=\"true\"}[$__rate_interval])) by (le))",
     "legendFormat": "0.5 (valid)"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{is_valid=\"true\"}[$__rate_interval])) by (le))",
     "legendFormat": "0.95 (valid)"
    },
    {
     "expr": "histogram_quantile(0.05, sum(rate(http_request_duration_seconds_bucket{is_valid=\"false\"}[$__rate_interval])) by (le))",
     "legendFormat": "0.05 (invalid)"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{is_valid=\"false\"}[$__rate_interval])) by (le))",
     "legendFormat": "0.5 (invalid)"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{is_valid=\"false\"}[$__rate_interval])) by (le))",
     "legendFormat": "0.95 (invalid)"
    }
   ]
  },
  {
   "title": "Price Prediction Quantiles (over time window)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.05, sum(rate(prediction_price_histogram_bucket[$__rate_interval])) by (le))",
     "legendFormat": "0.05"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(prediction_price_histogram_bucket[$__rate_interval])) by (le))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(prediction_price_histogram_bucket[$__rate_interval])) by (le))",
     "legendFormat": "0.95"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "description": "Rate of errors occurred up to each timestamp for each error type",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(invalid_request_count_total[$__rate_interval])",
     "legendFormat": "Invalid Requests"
    },
    {
     "expr": "rate(failed_predictions_count_total[$__rate_interval])",
     "legendFormat": "Failed Predictions"
    },
    {
     "expr": "rate(too_many_requests_count_total[$__rate_interval])",
     "legendFormat": "Too Many Requests Errors"
    },
    {
     "expr": "rate(unexpected_error_count_total[$__rate_interval])",
     "legendFormat": "Unexpected Errors"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[$__rate_interval]) * 100",
     "legendFormat": "App"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(process_virtual_memory_bytes[$__rate_interval]) * 100",
     "legendFormat": "Virtual Memory"
    },
    {
     "expr": "rate(process_resident_memory_bytes[$__rate_interval]) * 100",
     "legendFormat": "Resident Memory"
    }
   ]
  },
  {
   "title": "Prediction Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 22 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count{handler='/predict', is_valid=\"true\"}[$__rate_interval])",
     "legendFormat": "valid"
    },
    {
     "expr": "rate(http_request_duration_seconds_count{handler='/predict', is_valid=\"false\"}[$__rate_interval])",
     "legendFormat": "invalid"
    }
   ]
  }
 ]
}