FROM python:3.10.14-slim

LABEL author=${LABEL}

WORKDIR /fastapi_app/ml_service

COPY ./ml_service .
COPY .env .env

VOLUME /fastapi_app/models

EXPOSE ${APP_DOCKER_PORT}

RUN pip install -r requirements.txt

ENTRYPOINT ["/bin/bash", "entrypoints/entrypoint_single.sh"]